import { register, rng, type PuzzleDefinition } from './framework';

/**
 * CIRCUIT TABLE — the Innovation Laboratory, GDD Part 4 §6.
 *
 * A row of lamps and a row of switches. Every switch flips its own lamp and
 * both of its neighbours. Light them all.
 *
 * Generated by *unsolving*: start lit, press a random handful, hand the player
 * what is left. A board built that way is guaranteed solvable — press the same
 * switches again — which matters more here than anywhere else, because a
 * parity puzzle generated at random is unsolvable roughly half the time and the
 * player has no way to tell the difference between "hard" and "impossible".
 */

export interface CircuitState {
  readonly lamps: readonly boolean[];
}

export type CircuitInput = { readonly kind: 'press'; readonly at: number };

export const LAMP_COUNT = 7;

const press = (lamps: readonly boolean[], at: number): boolean[] =>
  lamps.map((lamp, index) => (Math.abs(index - at) <= 1 ? !lamp : lamp));

export const circuitTable: PuzzleDefinition<CircuitState, CircuitInput> = register({
  id: 'circuit-table',
  area: 'innovation-laboratory',
  title: 'The Circuit Table',
  premise: 'Every switch touches its neighbours. Nothing here moves alone.',
  targetSeconds: 150,

  initial: (seed): CircuitState => {
    const random = rng(seed);
    let lamps: boolean[] = Array.from({ length: LAMP_COUNT }, () => true);

    // Between three and six presses: enough to look daunting, never unsolvable.
    const presses = 3 + Math.floor(random() * 4);
    for (let i = 0; i < presses; i += 1) lamps = press(lamps, Math.floor(random() * LAMP_COUNT));

    // If the scramble happened to cancel itself out, disturb it once.
    if (lamps.every(Boolean)) lamps = press(lamps, Math.floor(random() * LAMP_COUNT));

    return { lamps };
  },

  apply: (state, input) =>
    input.at < 0 || input.at >= state.lamps.length ? state : { lamps: press(state.lamps, input.at) },

  validate: (state) => state.lamps.every(Boolean),

  /* Brute force over all 2^7 subsets. Every switch is its own inverse and the
     order of presses does not matter, so a subset is the whole search space —
     128 candidates, which is cheaper than being clever and impossible to get
     subtly wrong. */
  solve: (state) => {
    for (let mask = 0; mask < 1 << LAMP_COUNT; mask += 1) {
      let lamps = [...state.lamps];
      for (let at = 0; at < LAMP_COUNT; at += 1) if (mask & (1 << at)) lamps = press(lamps, at);
      if (lamps.every(Boolean)) return { lamps };
    }
    return state;
  },

  hints: [
    'A switch never flips only its own lamp.',
    'Pressing the same switch twice puts everything back. Order does not matter.',
    'Work from one end: fix the leftmost lamp, then never touch that switch again.',
  ],

  rewards: { memories: ['project-02', 'skill-04'], fragment: true },
});
