/* tokens.json -> CSS custom properties + TypeScript + GLSL constants + a Tailwind theme.
   The GLSL output is the point of this pipeline: the world's shaders and the Codex's
   stylesheet read the same palette, so the two layers cannot drift apart visually. */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { formatOklch, formatVec3, oklchToHex } from './color.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = resolve(root, 'src/generated');
const PREFIX = '--tfm';
const TIERS = ['global', 'semantic', 'component'];

const src = JSON.parse(readFileSync(resolve(root, 'tokens/tokens.json'), 'utf8'));

/* ── read the source tree ───────────────────────────────────────────── */

const flat = new Map(); // "global.color.cyan" -> { tier, group, name, raw }
for (const tier of TIERS) {
  for (const [group, entries] of Object.entries(src[tier] ?? {})) {
    for (const [name, raw] of Object.entries(entries)) {
      flat.set(`${tier}.${group}.${name}`, { tier, group, name, raw, css: `${PREFIX}-${group}-${name}` });
    }
  }
}

/* Two tokens in different tiers may not claim the same CSS name — that is a silent
   override in the cascade, which is exactly the drift this pipeline exists to stop. */
const byCssName = new Map();
for (const [path, t] of flat) {
  const clash = byCssName.get(t.css);
  if (clash) throw new Error(`Token name collision: ${t.css} is claimed by both ${clash} and ${path}`);
  byCssName.set(t.css, path);
}

/* ── resolve references ─────────────────────────────────────────────── */

const REF = /^\{([^}]+)\}(?:\s*\/\s*([0-9.]+))?$/;
const OKLCH = /^oklch\(\s*([\d.]+)%\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+)\s*)?\)$/;

const resolving = new Set();

/** @returns {{kind:'color', lch:number[], alpha:number} | {kind:'raw', value:string}} */
function resolve_(path) {
  const token = flat.get(path);
  if (!token) throw new Error(`Unknown token reference: {${path}}`);
  if (token.resolved) return token.resolved;
  if (resolving.has(path)) throw new Error(`Circular token reference at {${path}}`);
  resolving.add(path);

  const raw = String(token.raw).trim();
  let resolved;

  const ref = REF.exec(raw);
  const lch = OKLCH.exec(raw);

  if (ref) {
    const base = resolve_(ref[1]);
    if (ref[2] !== undefined) {
      if (base.kind !== 'color') throw new Error(`Alpha modifier applied to a non-colour token at ${path}`);
      resolved = { kind: 'color', lch: base.lch, alpha: Number(ref[2]) };
      token.aliasAlpha = Number(ref[2]);
    } else {
      resolved = base;
    }
    token.alias = ref[1];
  } else if (lch) {
    resolved = {
      kind: 'color',
      lch: [Number(lch[1]) / 100, Number(lch[2]), Number(lch[3])],
      alpha: lch[4] === undefined ? 1 : Number(lch[4]),
    };
  } else {
    resolved = { kind: 'raw', value: raw };
  }

  resolving.delete(path);
  token.resolved = resolved;
  return resolved;
}

for (const path of flat.keys()) resolve_(path);

const cssValue = (t) =>
  t.resolved.kind === 'color' ? formatOklch(t.resolved.lch, t.resolved.alpha) : t.resolved.value;

/* An aliased token emits var(--other) so a theme override at the global tier
   flows through the semantic tier at runtime rather than being baked in here. */
const cssEmitted = (t) => {
  if (!t.alias) return cssValue(t);
  const ref = `var(${flat.get(t.alias).css})`;
  /* color-mix keeps the reference live, so overriding a global colour for a theme
     still flows into every translucent token derived from it. */
  return t.aliasAlpha === undefined
    ? ref
    : `color-mix(in oklch, ${ref} ${Number((t.aliasAlpha * 100).toFixed(4))}%, transparent)`;
};

const banner = (what) =>
  `/* ${what}\n   GENERATED by scripts/build-tokens.mjs from tokens/tokens.json (Ember v${src.$version}).\n   Do not edit by hand — edit the source and run \`npm run tokens\`. */\n`;

/* ── 1 · CSS custom properties ──────────────────────────────────────── */

let css = banner('Ember design tokens · CSS custom properties');
css += ':root {\n';
for (const tier of TIERS) {
  css += `\n  /* ── ${tier} ── */\n`;
  let group = null;
  for (const t of flat.values()) {
    if (t.tier !== tier) continue;
    if (t.group !== group) { css += `\n`; group = t.group; }
    css += `  ${t.css}: ${cssEmitted(t)};\n`;
  }
}
css += '}\n';

/* ── 2 · TypeScript module ──────────────────────────────────────────── */

const tsName = (s) => (/^[A-Za-z_$][\w$]*$/.test(s) ? s : JSON.stringify(s));
let ts = banner('Ember design tokens · TypeScript');
ts += `\nexport const tokenVersion = ${JSON.stringify(src.$version)} as const;\n\n`;
ts += 'export const tokens = {\n';
for (const tier of TIERS) {
  ts += `  ${tier}: {\n`;
  const groups = [...new Set([...flat.values()].filter((t) => t.tier === tier).map((t) => t.group))];
  for (const group of groups) {
    ts += `    ${tsName(group)}: {\n`;
    for (const t of flat.values()) {
      if (t.tier !== tier || t.group !== group) continue;
      const hex = t.resolved.kind === 'color' ? oklchToHex(t.resolved.lch) : null;
      ts += `      ${tsName(t.name)}: { var: ${JSON.stringify(`var(${t.css})`)}, value: ${JSON.stringify(cssValue(t))}`;
      if (hex) ts += `, hex: ${JSON.stringify(hex)}, alpha: ${t.resolved.alpha}`;
      ts += ` },\n`;
    }
    ts += '    },\n';
  }
  ts += '  },\n';
}
ts += '} as const;\n\nexport type Tokens = typeof tokens;\n';

/* ── 3 · GLSL constants ─────────────────────────────────────────────── */

let glsl = banner('Ember design tokens · GLSL constants (linear space)');
glsl += '\n#ifndef EMBER_TOKENS_GLSL\n#define EMBER_TOKENS_GLSL\n\n';
const glslName = (t) => `TFM_${t.group}_${t.name}`.toUpperCase().replace(/[^A-Z0-9]+/g, '_');
for (const t of flat.values()) {
  if (t.tier !== 'semantic' || t.resolved.kind !== 'color') continue;
  glsl += `const vec3 ${glslName(t)} = ${formatVec3(t.resolved.lch)};\n`;
  if (t.resolved.alpha < 1) glsl += `const float ${glslName(t)}_A = ${t.resolved.alpha.toFixed(3)};\n`;
}
glsl += '\n#endif\n';

/* ── 4 · Tailwind v4 theme ──────────────────────────────────────────── */

let tw = banner('Ember design tokens · Tailwind theme');
tw += '\n@theme {\n';
for (const t of flat.values()) {
  if (t.tier !== 'semantic') continue;
  const ns = { color: 'color', space: 'spacing', radius: 'radius', type: 'text', motion: 'ease' }[t.group];
  if (!ns) continue;
  tw += `  --${ns}-${t.name}: var(${t.css});\n`;
}
tw += '}\n';

/* ── 5 · manifest, so the token gate knows which tier a name belongs to ─ */

const manifest = { version: src.$version, prefix: PREFIX, tiers: {} };
for (const tier of TIERS) manifest.tiers[tier] = [...flat.values()].filter((t) => t.tier === tier).map((t) => t.css);

mkdirSync(out, { recursive: true });
const files = {
  'tokens.css': css,
  'tokens.ts': ts,
  'tokens.glsl': glsl,
  'tokens.tailwind.css': tw,
  'tokens.manifest.json': JSON.stringify(manifest, null, 2) + '\n',
};
for (const [name, body] of Object.entries(files)) writeFileSync(resolve(out, name), body);

console.log(`tokens: ${flat.size} tokens -> ${Object.keys(files).join(', ')}`);
